# Generated by Django 4.0.2 on 2022-02-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raj', '0002_images_projectimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.FileField(upload_to='static/image'),
        ),
    ]
