# Generated by Django 4.0.2 on 2022-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raj', '0003_alter_images_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.FileField(upload_to='static/image')),
            ],
        ),
    ]
