# Generated by Django 4.0.2 on 2022-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raj', '0004_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.FileField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='projectimg',
            name='proimg',
            field=models.FileField(upload_to='static/image'),
        ),
    ]
